"use client";

import React, { useState, useEffect } from "react";
import { Search, PenSquare, MessageSquare, Settings2, ShieldAlert, DatabaseZap, Code2, Terminal } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';

export default function AgentPage() {
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState([
    { role: "agent", text: "Hello! I'm your Enterprise Intelligence Agent.\n\nI have federated SQL access to GitHub, SonarQube, Linear, and Sentry. What would you like to investigate?" }
  ]);
  const [coralData, setCoralData] = useState({ sql: "", explanation: "" });
  
  const [rightPanelWidth, setRightPanelWidth] = useState(400);
  const [isDragging, setIsDragging] = useState(false);

  useEffect(() => {
    const handleMouseMove = (e: MouseEvent) => {
      if (!isDragging) return;
      const newWidth = document.body.clientWidth - e.clientX;
      if (newWidth > 200 && newWidth < 800) {
        setRightPanelWidth(newWidth);
      }
    };
    const handleMouseUp = () => {
      setIsDragging(false);
    };
    if (isDragging) {
      document.addEventListener('mousemove', handleMouseMove);
      document.addEventListener('mouseup', handleMouseUp);
    }
    return () => {
      document.removeEventListener('mousemove', handleMouseMove);
      document.removeEventListener('mouseup', handleMouseUp);
    };
  }, [isDragging]);

  const handleInvestigate = async (presetQuery?: string) => {
    const textToSearch = presetQuery || query;
    if (!textToSearch.trim()) return;

    setHistory(prev => [...prev, { role: "user", text: textToSearch }]);
    setQuery("");
    setLoading(true);

    try {
      const backendUrl = process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8081";
      const response = await fetch(`${backendUrl}/api/investigate?repoName=demo-project&query=${encodeURIComponent(textToSearch)}`);
      let data = await response.text();
      
      // Extract Coral SQL and Explanation if present (fast-path responses embed them)
      let sqlMatch = data.match(/<SQL>([\s\S]*?)<\/SQL>/);
      let expMatch = data.match(/<EXPLANATION>([\s\S]*?)<\/EXPLANATION>/);
      
      if (sqlMatch || expMatch) {
        setCoralData({
          sql: sqlMatch ? sqlMatch[1].trim() : "",
          explanation: expMatch ? expMatch[1].trim() : ""
        });
        // Remove the XML tags from the visible chat message
        data = data.replace(/<SQL>[\s\S]*?<\/SQL>/g, "")
                   .replace(/<EXPLANATION>[\s\S]*?<\/EXPLANATION>/g, "")
                   .trim();
      } else {
        // LLM path — we don't have the SQL, but show a helpful note
        setCoralData({
          sql: `-- Intent: "${textToSearch}"\n-- This query was routed to the AI model.\n-- To see the exact SQL, ask a specific keyword\n-- e.g. "sonarqube metrics", "linear tasks", "sentry errors"`,
          explanation: "This response was generated by the AI model using the Coral MCP federated SQL tools. The exact SQL is determined dynamically by the model based on the schema discovery."
        });
      }

      setHistory(prev => [...prev, { role: "agent", text: data }]);
    } catch (error) {
      setHistory(prev => [...prev, { role: "agent", text: "⚠️ Error connecting to the backend." }]);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="flex h-full w-full bg-[#0a0a0a] text-neutral-200 font-sans">
      
      {/* Main Chat Panel */}
      <div className="flex-1 flex flex-col relative bg-[#0a0a0a]">
        <header className="px-8 py-6 border-b border-[#222]">
           <h1 className="text-xl font-bold text-white flex items-center">
             <Code2 className="w-6 h-6 mr-3 text-indigo-500" /> CoralOps Intelligence
           </h1>
           <p className="text-xs text-neutral-500 mt-1 uppercase tracking-widest">Federated Data Agent</p>
        </header>

        <div className="flex-1 overflow-y-auto p-8">
          <div className="max-w-4xl mx-auto space-y-8 pb-24">
            
            {history.length === 1 && (
              <div className="flex flex-col items-center justify-center mt-20 mb-12">
                <div className="w-16 h-16 bg-indigo-600/20 border border-indigo-500/50 rounded-2xl flex items-center justify-center shadow-[0_0_30px_rgba(79,70,229,0.1)] mb-6">
                  <DatabaseZap className="w-8 h-8 text-indigo-400" />
                </div>
                <h1 className="text-4xl font-semibold text-white mb-8">How can I help you today?</h1>
                <div className="flex space-x-4">
                  <button onClick={() => handleInvestigate("Discover the schemas for GitHub, Linear, SonarQube, and Sentry. Then write a SQL JOIN query connecting a GitHub PR to a Linear issue, and show me the lifecycle of this project.")} className="px-4 py-2 bg-[#1a1a1a] border border-[#333] hover:border-indigo-500 rounded-full text-sm transition-colors">Cross-Platform Join Demo</button>
                  <button onClick={() => handleInvestigate("Why is project quality poor?")} className="px-4 py-2 bg-[#1a1a1a] border border-[#333] hover:border-indigo-500 rounded-full text-sm transition-colors">Analyze Project Quality</button>
                </div>
              </div>
            )}

            <AnimatePresence>
              {history.map((msg, idx) => (
                <motion.div 
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  key={idx} 
                  className={`flex items-start ${msg.role === 'user' ? 'justify-end' : ''}`}
                >
                  {msg.role === 'agent' && (
                    <div className="w-8 h-8 rounded-lg bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center flex-shrink-0 mr-4 shadow-lg shadow-indigo-500/10 mt-1">
                      <ShieldAlert className="w-4 h-4 text-indigo-400" />
                    </div>
                  )}
                  <div className={`max-w-[85%] text-[13px] leading-relaxed ${
                    msg.role === 'user'
                      ? 'bg-neutral-800 text-white px-5 py-3 rounded-2xl rounded-tr-sm border border-neutral-700 whitespace-pre-wrap'
                      : 'text-neutral-300 px-2 py-1'
                  }`}>
                    {msg.role === 'agent' ? (
                      <ReactMarkdown
                        remarkPlugins={[remarkGfm]}
                        components={{
                          h2: ({children}) => <h2 className="text-sm font-bold text-white mt-3 mb-2 flex items-center gap-2">{children}</h2>,
                          h3: ({children}) => <h3 className="text-xs font-semibold text-indigo-300 mt-4 mb-1.5 uppercase tracking-wide">{children}</h3>,
                          p: ({children}) => <p className="text-[13px] text-neutral-300 mb-2 leading-relaxed">{children}</p>,
                          strong: ({children}) => <strong className="text-white font-semibold">{children}</strong>,
                          code: ({children}) => <code className="bg-[#1a1a1a] border border-[#2a2a2a] text-indigo-300 px-1.5 py-0.5 rounded text-[11px] font-mono">{children}</code>,
                          blockquote: ({children}) => (
                            <div className="border-l-2 border-indigo-500/40 pl-3 my-2 text-[12px] text-neutral-400 italic">{children}</div>
                          ),
                          hr: () => <hr className="border-[#222] my-3" />,
                          table: ({children}) => (
                            <div className="overflow-x-auto my-3">
                              <table className="w-full text-[11px] border-collapse">{children}</table>
                            </div>
                          ),
                          thead: ({children}) => <thead className="bg-[#111]">{children}</thead>,
                          th: ({children}) => <th className="px-3 py-1.5 text-left text-[10px] text-neutral-500 font-semibold uppercase tracking-wider border-b border-[#222]">{children}</th>,
                          tr: ({children}) => <tr className="border-b border-[#1a1a1a] hover:bg-[#0f0f0f] transition-colors">{children}</tr>,
                          td: ({children}) => <td className="px-3 py-1.5 text-neutral-300">{children}</td>,
                          li: ({children}) => <li className="text-[13px] text-neutral-300 mb-1 ml-4 list-disc">{children}</li>,
                          ul: ({children}) => <ul className="my-2 space-y-1">{children}</ul>,
                          ol: ({children}) => <ol className="my-2 space-y-1 list-decimal ml-4">{children}</ol>,
                        }}
                      >
                        {msg.text}
                      </ReactMarkdown>
                    ) : (
                      msg.text
                    )}
                  </div>
                </motion.div>
              ))}
            </AnimatePresence>

            {loading && (
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="flex items-start">
                <div className="w-8 h-8 rounded-lg bg-indigo-600/20 border border-indigo-500/30 flex items-center justify-center flex-shrink-0 mr-4 mt-1">
                  <ShieldAlert className="w-4 h-4 text-indigo-400" />
                </div>
                <div className="px-2 py-3 flex space-x-2 items-center h-8">
                  <div className="w-2 h-2 bg-neutral-500 rounded-full animate-bounce"></div>
                  <div className="w-2 h-2 bg-neutral-500 rounded-full animate-bounce delay-75"></div>
                  <div className="w-2 h-2 bg-neutral-500 rounded-full animate-bounce delay-150"></div>
                </div>
              </motion.div>
            )}
          </div>
        </div>

        {/* Input Box */}
        <div className="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-[#0a0a0a] via-[#0a0a0a] to-transparent">
          <div className="max-w-4xl mx-auto">
            <form onSubmit={(e) => { e.preventDefault(); handleInvestigate(); }} className="relative">
              <input 
                type="text" 
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                disabled={loading}
                placeholder="Ask CoralOps Agent..." 
                className="w-full bg-[#111] border border-[#333] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 rounded-full pl-6 pr-14 py-4 text-white placeholder-neutral-500 outline-none transition-all shadow-xl"
              />
              <button 
                type="submit" 
                disabled={loading || !query.trim()}
                className="absolute right-2 top-2 bottom-2 w-10 bg-indigo-600 hover:bg-indigo-500 disabled:bg-[#333] rounded-full flex items-center justify-center transition-colors"
              >
                <div className="w-4 h-4 border-t-2 border-r-2 border-white transform rotate-45 mr-1"></div>
              </button>
            </form>
          </div>
        </div>
      </div>

      {/* Draggable Divider */}
      <div 
        className={`hidden xl:block w-1 cursor-col-resize z-50 transition-colors ${isDragging ? 'bg-indigo-500' : 'bg-[#222] hover:bg-indigo-500/50'}`}
        onMouseDown={(e) => { e.preventDefault(); setIsDragging(true); }}
      />

      {/* Right Tools Panel: Coral Query Showcase */}
      <div 
        className="hidden xl:flex flex-col border-l border-[#222] bg-[#111]"
        style={{ width: rightPanelWidth }}
      >
         <div className="p-6 border-b border-[#222]">
            <h2 className="text-sm font-bold text-white uppercase tracking-widest flex items-center">
              <DatabaseZap className="w-4 h-4 mr-2 text-emerald-400" /> Coral Query
            </h2>
            <p className="text-xs text-neutral-500 mt-2 leading-relaxed">
              Real-time insight into the federated SQL executed by the Agent across your connected tools.
            </p>
         </div>

         <div className="flex-1 p-6 overflow-y-auto space-y-6">
            {!coralData.sql && !loading && (
              <div className="h-full flex flex-col items-center justify-center text-neutral-600">
                 <Terminal className="w-12 h-12 mb-4 opacity-20" />
                 <p className="text-sm">Awaiting query execution...</p>
              </div>
            )}

            {loading && (
              <div className="animate-pulse space-y-4">
                 <div className="h-4 bg-[#222] rounded w-1/3"></div>
                 <div className="h-32 bg-[#1a1a1a] rounded border border-[#333]"></div>
                 <div className="h-4 bg-[#222] rounded w-1/4 mt-8"></div>
                 <div className="h-16 bg-[#1a1a1a] rounded border border-[#333]"></div>
              </div>
            )}

            {coralData.sql && !loading && (
              <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="space-y-8">
                 
                 <div>
                    <h3 className="text-xs font-semibold text-neutral-400 uppercase tracking-widest mb-3">Executed SQL</h3>
                    <div className="bg-[#050505] border border-[#222] rounded-xl p-4 overflow-x-auto relative group">
                       <div className="absolute top-0 left-0 w-1 h-full bg-emerald-500"></div>
                       <pre className="text-[11px] text-emerald-400 font-mono leading-relaxed whitespace-pre-wrap">
                         {coralData.sql}
                       </pre>
                    </div>
                 </div>

                 {coralData.explanation && (
                   <div>
                      <h3 className="text-xs font-semibold text-neutral-400 uppercase tracking-widest mb-3">Query Logic</h3>
                      <div className="bg-[#1a1a1a] border border-[#333] rounded-xl p-4 text-sm text-neutral-300 leading-relaxed">
                         {coralData.explanation}
                      </div>
                   </div>
                 )}

                 <div className="pt-4 border-t border-[#222]">
                    <div className="flex items-center justify-between text-xs text-neutral-500">
                       <span className="flex items-center"><ShieldAlert className="w-3 h-3 mr-1 text-yellow-500" /> Read-only mode</span>
                       <span>Coral Engine v0.3.0</span>
                    </div>
                 </div>

              </motion.div>
            )}
         </div>
      </div>

    </div>
  );
}
